script: bash ./deploy.sh
language: node_js
node_js:
  - "0.10"
env:
  global:
  - GH_REF: github.com/websemanticsio/the-ten-commandments-for-exceptional-developers.git
  - secure: DHnTr6JuUPsa4LangE6M9/n9InNrkP/tDjQ6/UNfaVvwyGXjPORbzu/hsxQbAZlCPpaps33Q52/XfYW84PsJuE+FGFCxKdWFlR4NcKHSicPoF8qlbE1IFbmve3bs7GfAArb5dtAm9YKjkUtC74Z4Y6wvzVGgfYAxoBLCF7WULYeqsaUnDCXzaOdfbIq9H2wErZvk357ME5WkxWZvVFCZsFJZb2kqetK9MDVC/XAQPN7SIN1jMvYoCTadbhuvpC2MvCmAjqnOjEbOIhiCOOPX3IFXZIYO/1bsT2NO7NdiGHgqQ4tOET1jaCRM6LynlpCB6+DqwfiWaQpxGX6SCktYi1au5Xtqq9nDWguthVEHuKaaMtmEz0BhPtdAd45og0kVeuEFOMFiNHt1Tn0fwIfTlr3ZQCa3SS7reqikbnS9HNr+8mDWrm08LxhU1+gYYEyrg8zSFFfUIlGXx5TuQAThK325bI0GarL3eeYB8umsR+nEb83vpUOBO6x7B35t2hUqSoOXbYEz1I+HjJn6UOJLwb94pAaYxCW0PF9mpSgwgYNVziVj3nG1lmA17vKkKbgh0Mp5m8SUmOloabe4YB7HXOt+fYSegAh8fY509Jz2dz+b7nBvLTqbRoWTdaMVQHwOyiSDuDYdYzSL7Gm2noTNUbKpVLYmdxFdned9g5frNDQ=
